/* Minimal system_stm32f10x.c placeholder
   Replace with the vendor-provided system_stm32f10x.c generated by CubeMX for correct clock setup.
*/
#include "stm32f1xx_hal.h"

void SystemInit(void) {
  /* Placeholder: actual clock init is generated by CubeMX */
}

/* Optional SystemCoreClock variable */
uint32_t SystemCoreClock = 72000000;
